
spring:
  application:
    name: device-demo
  datasource:
    url: jdbc:mysql://localhost:3306/equipment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root#123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 100
      maximum-pool-size: 100
      connection-test-query: SELECT 1
#mybatis:
#  mapper-locations: classpsth:com.jc.local.mapper/*.xml
#  type-aliases-package: com.jc.local.entity

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jc.local.entity
server:
  port: 9090

http:
  maxTotal: 100

  defaultMaxPerRoute: 20

  connectTimeout: 1000

  connectionRequestTimeout: 500

  socketTimeout: 10000

  staleConnectionCheckEnabled: true


